### ISSUE TITLE
rubygems.org link to this gem's homepage appears to be outdated

### ISSUE THREAD

**Issue by jordanstephens** [christianv/ravenjs-gem#2]
The link to this gem's "Homepage" at https://rubygems.org/gems/ravenjs-gem points to [ets-berkeley-edu/ravenjs-gem](https://github.com/ets-berkeley-edu/ravenjs-gem), rather than to this repo.

The linked repo appears to be two versions out of date, while this one appears to be slightly more recently updated.

Assuming that this repo is the more "official" repo, you may want to update the link on the rubygems page.

For example: the issue that was solved with #1 is still presented in the linked repo's README.

**Comment by christianv** [comment]
@jordanstephens thanks for raising this. [ets-berkeley-edu/ravenjs-gem](https://github.com/ets-berkeley-edu/ravenjs-gem) is actually the official repo and I've updated it
